
name: deploy to heroku

on: workflow_dispatch

jobs:
  build:
    name: Builde and deploy to heroku
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install -g heroku 
      - run: |
          printf "machine api.heroku.com\n  login ${{secrets.HEROKU_EMAIL}}\n  password ${{secrets.HEROKU_API_KEY}}\nmachine git.heroku.com\n  login ${{secrets.HEROKU_EMAIL}}\n  password ${{secrets.HEROKU_API_KEY}}" | cat > ~/.netrc
      - run: heroku login
      - run: heroku config:set --app ${{secrets.HEROKU_APP_NAME}} MONGO_URL=${{secrets.DB_CONNECTION_STRING}}
      - run: heroku container:login
      - run: heroku container:push web --app ${{secrets.HEROKU_APP_NAME}} --arg APP_BUILD_SERVER_URL="${{secrets.APP_URL}}"
      - run: heroku container:release web --app ${{secrets.HEROKU_APP_NAME}}
